import type { Asset, AuditEntry, Person, TransferOptions } from './types'

export const fmtDate = (s?: string) => (s ? new Date(s).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : '—')

export function ago(s?: string) {
  if (!s) return '—'
  const d = Math.floor((Date.now() - new Date(s).getTime()) / 864e5)
  return d <= 0 ? 'today' : d < 31 ? `${d}d ago` : d < 365 ? `${Math.floor(d / 30)}mo ago` : `${Math.floor(d / 365)}y ago`
}

export function download(name: string, text: string, type = 'text/plain') {
  const url = URL.createObjectURL(new Blob([text], { type }))
  const a = document.createElement('a')
  a.href = url
  a.download = name
  a.click()
  URL.revokeObjectURL(url)
}

const csvCell = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`

export function toCsv(rows: Record<string, unknown>[]) {
  if (!rows.length) return ''
  const cols = Object.keys(rows[0])
  return [cols.join(','), ...rows.map((r) => cols.map((c) => csvCell(r[c])).join(','))].join('\n')
}

export const assetRows = (a: Asset[]) =>
  a.map((x) => ({ Type: x.kind, Name: x.name, Environment: x.envName, EnvironmentId: x.envId, Id: x.id, Owner: x.ownerEmail, State: x.state, Modified: x.modifiedTime ?? '', Solution: x.inSolution ? 'yes' : 'no', Connections: x.connections ?? 0 }))

export const auditRows = (a: AuditEntry[]) =>
  a.map((x) => ({ When: x.at, Batch: x.batch, DryRun: x.dryRun, Type: x.kind, Name: x.name, Environment: x.envName, From: x.from.email, To: x.to.email, Mode: x.mode, Status: x.status, Error: x.error ?? '' }))

/** Equivalent PowerShell (Microsoft.PowerApps.Administration.PowerShell) - handy for change tickets / audits. */
export function powershellFor(assets: Asset[], to: Person, opts: TransferOptions) {
  const lines = [
    '# Generated by Ownership Command Center',
    'Install-Module Microsoft.PowerApps.Administration.PowerShell -Scope CurrentUser',
    'Add-PowerAppsAccount',
    '',
  ]
  for (const a of assets) {
    if (a.kind === 'app') lines.push(`Set-AdminPowerAppOwner -AppName '${a.id}' -EnvironmentName '${a.envId}' -AppOwner '${to.id}'  # ${a.name}`)
    else {
      lines.push(`Set-AdminFlowOwnerRole -EnvironmentName '${a.envId}' -FlowName '${a.id}' -RoleName CanEdit -PrincipalType User -PrincipalObjectId '${to.id}'  # ${a.name}`)
      if (opts.mode === 'replace' && opts.removeOldOwner) lines.push(`Remove-AdminFlowOwnerRole -EnvironmentName '${a.envId}' -FlowName '${a.id}' -RoleId '${a.ownerId}'`)
    }
  }
  return lines.join('\n')
}

export interface Risk { level: 'warn' | 'info'; text: string }
export function risksFor(a: Asset): Risk[] {
  const r: Risk[] = []
  if (a.inSolution) r.push({ level: 'warn', text: 'Solution-aware: ownership may be governed by the solution / connection references.' })
  if (a.kind === 'flow' && (a.connections ?? 0) > 0) r.push({ level: 'warn', text: `${a.connections} connection(s) use the old owner's credentials - re-authenticate after transfer.` })
  if (a.kind === 'flow' && a.state !== 'Started') r.push({ level: 'info', text: `Flow is ${a.state}.` })
  if (a.kind === 'app') r.push({ level: 'info', text: 'Apps have a single owner; the previous owner keeps no ownership.' })
  return r
}
