import type { Asset, AssetKind, AuditEntry, Person, TransferOptions } from './types'

export const fmtDate = (s?: string) => (s ? new Date(s).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : '—')

export function ago(s?: string) {
  if (!s) return '—'
  const d = Math.floor((Date.now() - new Date(s).getTime()) / 864e5)
  return d <= 0 ? 'today' : d < 31 ? `${d}d ago` : d < 365 ? `${Math.floor(d / 30)}mo ago` : `${Math.floor(d / 365)}y ago`
}

export function download(name: string, text: string, type = 'text/plain') {
  const url = URL.createObjectURL(new Blob([text], { type }))
  const a = document.createElement('a')
  a.href = url
  a.download = name
  a.click()
  URL.revokeObjectURL(url)
}

const csvCell = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`

export function toCsv(rows: Record<string, unknown>[]) {
  if (!rows.length) return ''
  const cols = Object.keys(rows[0])
  return [cols.join(','), ...rows.map((r) => cols.map((c) => csvCell(r[c])).join(','))].join('\n')
}

export const assetRows = (a: Asset[]) =>
  a.map((x) => ({ Type: x.kind, Name: x.name, Environment: x.envName, EnvironmentId: x.envId, Id: x.id, Owner: x.ownerEmail, State: x.state, Modified: x.modifiedTime ?? '', Solution: x.inSolution ? 'yes' : 'no', Connections: x.connections ?? 0 }))

export const auditRows = (a: AuditEntry[]) =>
  a.map((x) => ({ When: x.at, Batch: x.batch, DryRun: x.dryRun, Type: x.kind, Name: x.name, Environment: x.envName, From: x.from.email, To: x.to.email, Mode: x.mode, Status: x.status, Error: x.error ?? '' }))

/** Equivalent PowerShell (Microsoft.PowerApps.Administration.PowerShell) - handy for change tickets / audits. */
export function powershellFor(assets: Asset[], to: Person, opts: TransferOptions) {
  const lines = [
    '# Generated by Ownership Command Center',
    'Install-Module Microsoft.PowerApps.Administration.PowerShell -Scope CurrentUser',
    'Add-PowerAppsAccount',
    '',
  ]
  for (const a of assets) {
    if (a.kind === 'agent') lines.push(`# Copilot Studio agent '${a.name}' (${a.envName}): PATCH https://${a.orgHost && !['inventory', 'native'].includes(a.orgHost) ? a.orgHost : '<org host>'}/api/data/v9.2/bots(${a.id})  body: { "ownerid@odata.bind": "/systemusers(<new owner's systemuserid in that environment>)" }`)
    else if (a.kind === 'app') lines.push(`Set-AdminPowerAppOwner -AppName '${a.id}' -EnvironmentName '${a.envId}' -AppOwner '${to.id}'  # ${a.name}`)
    else {
      lines.push(`Set-AdminFlowOwnerRole -EnvironmentName '${a.envId}' -FlowName '${a.id}' -RoleName CanEdit -PrincipalType User -PrincipalObjectId '${to.id}'  # ${a.name}`)
      if (opts.mode === 'replace' && opts.removeOldOwner) lines.push(`Remove-AdminFlowOwnerRole -EnvironmentName '${a.envId}' -FlowName '${a.id}' -RoleId '${a.ownerId}'`)
    }
  }
  return lines.join('\n')
}

export interface Risk { level: 'warn' | 'info'; text: string }
export function risksFor(a: Asset): Risk[] {
  const r: Risk[] = []
  if (a.inSolution) r.push({ level: 'warn', text: 'Solution-aware: ownership may be governed by the solution / connection references.' })
  if (a.kind === 'flow' && (a.connections ?? 0) > 0) r.push({ level: 'warn', text: `${a.connections} connection(s) use the old owner's credentials - re-authenticate after transfer.` })
  if (a.kind === 'flow' && a.state !== 'Started') r.push({ level: 'info', text: `Flow is ${a.state}.` })
  if (a.kind === 'app') r.push({ level: 'info', text: 'Apps have a single owner; the previous owner keeps no ownership.' })
  if (a.kind === 'agent') {
    r.push({ level: 'warn', text: 'Copilot Studio agent: your connection account needs System Administrator in that environment, and the new owner must be a member of that environment with a Copilot licence. Re-check connections, channels and publishing afterwards.' })
    r.push({ level: 'info', text: 'Agents have a single owner (co-owner mode does not apply).' })
  }
  return r
}

/** True when the service says an agent reassignment started but did not finish (agent may be half-updated). */
export const isPartialUpdate = (err: string) => /partially updated|only partially/i.test(err) || (/HTTP 502/i.test(err) && /not in a json format/i.test(err))

/** Turn a raw connector error into plain-language likely causes (shown under a failed transfer). */
export function explainTransferError(err: string, kind: AssetKind): string[] {
  const e = err.toLowerCase()
  const tips: string[] = []
  if (kind === 'agent' && isPartialUpdate(err)) {
    tips.push('⚠ The service started the reassignment but could not finish ("only partially updated"). The agent may be half-updated and may not work until a reassignment SUCCEEDS. Fix the cause below, then click Retry – or click "Restore original owner".')
    tips.push('Microsoft\'s documented requirements for the new owner: (1) a Copilot Studio / Microsoft 365 Copilot licence and (2) being a MEMBER of the agent\'s environment. Note: System Customizer is NOT in Microsoft\'s requirements – it only appears in a community fix, most likely because adding any role creates the user\'s record in the environment.')
    tips.push('The transfer panel can do this for you: keep "Add the new owner to each agent\'s environment first" ticked (it uses the official Add Admin Power Apps Sync User operation – membership only, no roles). Manual alternative: Power Platform admin center → Environments → (the agent\'s environment) → Users → Add user → add them with the lowest role (e.g. Environment Maker). The reassignment itself then grants Environment Maker automatically. Wait 1-2 minutes and Retry.')
    tips.push('Only if that still fails: temporarily add System Customizer (what the community report used), retry, then remove it.')
    tips.push('Tell licence problems from agent problems: try the SAME agent with a different, fully licensed Copilot Studio user as new owner. If that works, the original target user is the problem (licence not provisioned / cannot open Copilot Studio). If it also fails, the agent or environment is the problem.')
    tips.push('Agents left half-updated: re-run the reassignment (to the same new owner once prerequisites are fixed, or back to the original owner via History → Restore). Verify by opening the agent in Copilot Studio as its owner.')
    tips.push('Generic HTTP 502 "The response is not in a JSON format" is how the connector reports these refusals.')
  }
  if (/405|method not allowed/.test(e) && kind === 'agent') tips.push('HTTP 405: classic (pre-agent) chatbots are not supported by the reassign API. Use Power Apps → Solutions → the agent → Assign, or the admin center.')
  if (/403|forbidden|unauthor|access is denied|privilege|permission/.test(e))
    tips.push('Permission: the account signed in to the connection must be a Power Platform / AI / tenant admin AND hold the System Administrator role in the item\'s environment.')
  if (/licen/.test(e)) tips.push('Licence: the new owner needs an active licence (for agents: Microsoft 365 Copilot).')
  if (/managed|solution|locked/.test(e)) tips.push('The item is in a managed solution. Make an unmanaged customization (open it, small edit, save) or change the owner in the Power Platform admin center.')
  if (/not found|does not exist|no user|systemuser|user record/.test(e)) tips.push('The new owner must exist as a user in the item\'s environment (add them to the environment first).')
  if (kind === 'agent') {
    tips.push('Agent checklist: the new owner is a member (user) of the agent\'s environment, has a Copilot Studio / Microsoft 365 Copilot licence, and the agent is not a classic chatbot.')
  } else if (kind === 'app') tips.push('The new owner must be a licensed user in the tenant; apps in managed solutions cannot be re-owned.')
  else tips.push('For flows the new owner must have a licence that allows the flow\'s connectors; solution flows may need their connection references re-pointed.')
  return [...new Set(tips)]
}
